DEVOPS-95 Script for sending copies of backup files to ARIS HPC.
ARGOeu/argo-utils pull request #3
Opened 2020-04-02 17:16 UTC by Tas-sos

This is my script to sync backup files with data center.

2020-04-02 20:36 UTC, themiszamani requested changes

2020-04-02 20:36 UTC, themiszamani commented on rSync_data_with_dataCenter/rSyncBackups.sh
> +	echo -e "| Backup of files to host \e[91m$REMOTE_HOST\e[97m \e[92m\e[1mcompleted\e[97m\e[21m at \e[34m`date`\e[97m \t|"
encoding

2020-04-02 20:36 UTC, themiszamani commented on rSync_data_with_dataCenter/rSyncBackups.sh
> +done
i think we need some default values. Maybe the remote host.

2020-04-03 05:03 UTC, Tas-sos commented on rSync_data_with_dataCenter/rSyncBackups.sh
> +done
Thank you for review Τhemis,

The reason I don't have a default value is that I designed and implemented it to make it as dynamic as possible.
But if you wanted default values,  no problem.

2020-04-09 19:48 UTC, themiszamani reviewed
i dont see the multiple directories.

2020-04-09 19:48 UTC, themiszamani commented on rSync_data_with_dataCenter/rSyncBackups.sh
> +		echo -e "rSync Backaps."
small typo ;) Backups

2020-04-10 07:30 UTC, Tas-sos commented on rSync_data_with_dataCenter/rSyncBackups.sh
> +/usr/bin/rsync -avzh --progress -e "ssh -o StrictHostKeyChecking=no -i $SSH_KEY -va" ${FROM_DIR[@]} $REMOTE_USER@$REMOTE_HOST:$REMOTE_PARENT_DIR
@themiszamani 
Νow sends either one or all of the paths it has taken from the user.
Now the variable `${FROM_DIR[@]}` is a **array**.

2020-05-21 18:18 UTC, merged